#!/usr/bin/env bash
# Build the SerpLumen .mcaddon from the bp/ (behavior) and rp/ (resource) packs.
#
# Version comes from bp/manifest.json (header.version). At package time each
# pack is copied into a versioned folder (SerpLumen<ver>B / SerpLumen<ver>R) and
# the two folders are zipped DIRECTLY into the .mcaddon. Minecraft (especially
# iOS/Bedrock) only recurses into folders and .mcpack files when importing a
# .mcaddon - it does NOT open inner .zip files, so a nested a.zip/b.zip layout
# imports as "Unknown Pack". Keeping the pack folders at the archive root is the
# universally-importable structure.
set -euo pipefail
cd "$(dirname "$0")"

BP=bp
RP=rp

VERDOT=$(node -e "console.log(JSON.parse(require('fs').readFileSync('$BP/manifest.json','utf8')).header.version.join('.'))")
VERUS=${VERDOT//./_}
OUT="dist/SerpLumen_v${VERUS}.mcaddon"

echo "version=$VERDOT  ->  $OUT"

# both manifests must parse
for m in "$BP/manifest.json" "$RP/manifest.json"; do
  node -e "JSON.parse(require('fs').readFileSync('$m','utf8'))" || { echo "bad manifest: $m"; exit 1; }
done

# auto-register bundled .mcstructure files -> scripts/bundled_structures.js
# (identifier: structures/<ns>/<name>.mcstructure -> "<ns>:<name>", or a file
#  directly in structures/ -> "mystructure:<name>")
node -e '
const fs=require("fs"),path=require("path");
const root=process.argv[1]+"/structures"; let out=[];
(function walk(d){ if(!fs.existsSync(d))return;
  for(const f of fs.readdirSync(d)){ const p=path.join(d,f); const st=fs.statSync(p);
    if(st.isDirectory()) walk(p);
    else if(f.endsWith(".mcstructure")){
      const rel=path.relative(root,p).split(path.sep).join("/");
      const noext=rel.replace(/\.mcstructure$/,"");
      const i=noext.indexOf("/");
      const id = i<0 ? ("mystructure:"+noext) : (noext.slice(0,i)+":"+noext.slice(i+1));
      out.push({ id, name: noext.split("/").pop().replace(/_/g," ") });
    } } })(root);
out.sort((a,b)=>a.id.localeCompare(b.id));
fs.writeFileSync(process.argv[1]+"/scripts/bundled_structures.js",
  "// AUTO-GENERATED by build.sh from bp/structures/*.mcstructure - do not edit by hand.\nexport const BUNDLED = "+JSON.stringify(out,null,2)+";\n");
console.log("bundled structures registered:", out.length);
' "$BP"

# syntax-check every script before packaging
for f in "$BP"/scripts/*.js; do node --check "$f"; done
echo "all scripts pass node --check"

TMP=$(mktemp -d)
cp -r "$BP" "$TMP/SerpLumen${VERUS}B"
cp -r "$RP" "$TMP/SerpLumen${VERUS}R"
(
  cd "$TMP"
  zip -r -X -q addon.mcaddon "SerpLumen${VERUS}B" "SerpLumen${VERUS}R"
)
mkdir -p dist
rm -f "$OUT"
mv "$TMP/addon.mcaddon" "$OUT"
rm -rf "$TMP"

echo "built $OUT ($(du -h "$OUT" | cut -f1))"
