// Auto-generated tu SERP Pokedrock v1.32.5 BP (240 items)
export const SERP_ITEMS = [
    { id: "serp:navigator", name: "Navigator (SERP Essentials)" },
    { id: "serp:config", name: "Config Menu Admin (SERP Essentials)" },
    { id: "serp:crates", name: "Crates (SERP Essentials)" },
    { id: "serp:absolite", name: "Absolite" },
    { id: "serp:aerodactylite", name: "Aerodactylite" },
    { id: "serp:alakazite", name: "Alakazite" },
    { id: "serp:ampharosite", name: "Ampharosite" },
    { id: "serp:ancient_amber", name: "Ancient Amber" },
    { id: "serp:articuno_feather", name: "Articuno Feather" },
    { id: "serp:ash_boots", name: "Ash Boots" },
    { id: "serp:ash_chestplate", name: "Ash Chestplate" },
    { id: "serp:ash_helmet", name: "Ash Helmet" },
    { id: "serp:ash_leggings", name: "Ash Leggings" },
    { id: "serp:aspear_berry", name: "Aspear Berry" },
    { id: "serp:auspicious_armor", name: "Auspicious Armor" },
    { id: "serp:bad_egg", name: "Bad Egg" },
    { id: "serp:badge", name: "Badge" },
    { id: "serp:banettite", name: "Youettite" },
    { id: "serp:base_backpack", name: "Base Backpack" },
    { id: "serp:beastball", name: "Beastball" },
    { id: "serp:beedrillite", name: "Beedrillite" },
    { id: "serp:black_apricorn", name: "Black Apricorn" },
    { id: "serp:black_belt", name: "Black Belt" },
    { id: "serp:black_glasses", name: "Black Glasses" },
    { id: "serp:blastoisinite", name: "Blastoisinite" },
    { id: "serp:blazikenite", name: "Blazikenite" },
    { id: "serp:blue_apricorn", name: "Blue Apricorn" },
    { id: "serp:blue_prism", name: "Blue Prism" },
    { id: "serp:blue_ribbon", name: "Blue Ribbon" },
    { id: "serp:calcium", name: "Calcium" },
    { id: "serp:carbos", name: "Carbos" },
    { id: "serp:charcoal", name: "Charcoal" },
    { id: "serp:charizardite_x", name: "Charizardite X" },
    { id: "serp:charizardite_y", name: "Charizardite Y" },
    { id: "serp:cheri_berry", name: "Cheri Berry" },
    { id: "serp:cherishball", name: "Cherishball" },
    { id: "serp:chesto_berry", name: "Chesto Berry" },
    { id: "serp:clefairy_plush", name: "Clefairy Plush" },
    { id: "serp:communicator", name: "Communicator" },
    { id: "serp:cooked_slowpoke_tail", name: "Cooked Slowpoke Tail" },
    { id: "serp:cyan_apricorn", name: "Cyan Apricorn" },
    { id: "serp:dawn_stone", name: "Dawn Stone" },
    { id: "serp:deoxys_virus", name: "Deoxys Virus" },
    { id: "serp:diveball", name: "Diveball" },
    { id: "serp:dragon_fang", name: "Dragon Fang" },
    { id: "serp:dreamball", name: "Dreamball" },
    { id: "serp:dusk_stone", name: "Dusk Stone" },
    { id: "serp:duskball", name: "Duskball" },
    { id: "serp:dynamax_band", name: "Dynamax Youd" },
    { id: "serp:dynamax_candy", name: "Dynamax Candy" },
    { id: "serp:emboarite", name: "Emboarite" },
    { id: "serp:enigma_berry", name: "Enigma Berry" },
    { id: "serp:entei_lock", name: "Entei Lock" },
    { id: "serp:exp_share", name: "Exp Share" },
    { id: "serp:fairy_feather", name: "Fairy Feather" },
    { id: "serp:fastball", name: "Fastball" },
    { id: "serp:fire_stone", name: "Fire Stone" },
    { id: "serp:focus_band", name: "Focus Youd" },
    { id: "serp:fossil_dome", name: "Fossil Dome" },
    { id: "serp:fossil_helix", name: "Fossil Helix" },
    { id: "serp:fresh_water", name: "Fresh Water" },
    { id: "serp:friendball", name: "Friendball" },
    { id: "serp:full_heal", name: "Full Heal" },
    { id: "serp:full_restore", name: "Full Restore" },
    { id: "serp:galladite", name: "Galladite" },
    { id: "serp:garchompite", name: "Gartompite" },
    { id: "serp:gardevoirite", name: "Gardevoirite" },
    { id: "serp:gengarite", name: "Gengarite" },
    { id: "serp:greatball", name: "Greatball" },
    { id: "serp:green_apricorn", name: "Green Apricorn" },
    { id: "serp:green_boots", name: "Green Boots" },
    { id: "serp:green_chestplate", name: "Green Chestplate" },
    { id: "serp:green_helmet", name: "Green Helmet" },
    { id: "serp:green_leggings", name: "Green Leggings" },
    { id: "serp:green_prism", name: "Green Prism" },
    { id: "serp:greninjite", name: "Greninjite" },
    { id: "serp:grepa_berry", name: "Grepa Berry" },
    { id: "serp:groudon_claw", name: "Groudon Claw" },
    { id: "serp:gyaradosite", name: "Gyaradosite" },
    { id: "serp:hard_stone", name: "Hard Stone" },
    { id: "serp:healball", name: "Healball" },
    { id: "serp:healing_machine", name: "Healing Machine" },
    { id: "serp:heavyball", name: "Heavyball" },
    { id: "serp:heracronite", name: "Heracronite" },
    { id: "serp:hondew_berry", name: "Hondew Berry" },
    { id: "serp:hoopa_ring_item", name: "Hoopa Ring Item" },
    { id: "serp:hp_up", name: "Hp Up" },
    { id: "serp:hyper_potion", name: "Hyper Potion" },
    { id: "serp:ice_stone", name: "Ice Stone" },
    { id: "serp:iron", name: "Iron" },
    { id: "serp:kangaskhanite", name: "Kangaskhanite" },
    { id: "serp:kelpsy_berry", name: "Kelpsy Berry" },
    { id: "serp:key_shard", name: "Key Shard" },
    { id: "serp:key_stone", name: "Key Stone" },
    { id: "serp:kings_rock", name: "Kings Rock" },
    { id: "serp:kyogre_fang", name: "Kyogre Fang" },
    { id: "serp:leaf_stone", name: "Leaf Stone" },
    { id: "serp:leftovers", name: "Leftovers" },
    { id: "serp:lemonade", name: "Lemonade" },
    { id: "serp:levelball", name: "Levelball" },
    { id: "serp:linking_cord", name: "Linking Cord" },
    { id: "serp:loveball", name: "Loveball" },
    { id: "serp:lucarionite", name: "Lucarionite" },
    { id: "serp:lum_berry", name: "Lum Berry" },
    { id: "serp:lureball", name: "Lureball" },
    { id: "serp:luxuryball", name: "Luxuryball" },
    { id: "serp:magnet", name: "Magnet" },
    { id: "serp:mago_berry", name: "Mago Berry" },
    { id: "serp:malicious_armor", name: "Malicious Armor" },
    { id: "serp:masterball", name: "Masterball" },
    { id: "serp:mawilite", name: "Mawilite" },
    { id: "serp:max_elixir", name: "Max Elixir" },
    { id: "serp:max_potion", name: "Max Potion" },
    { id: "serp:max_repel", name: "Max Repel" },
    { id: "serp:max_revive", name: "Max Revive" },
    { id: "serp:mega_ring", name: "Mega Ring" },
    { id: "serp:metal_coat", name: "Metal Coat" },
    { id: "serp:mew_dna", name: "Mew Dna" },
    { id: "serp:mewtwonite_x", name: "Mewtwonite X" },
    { id: "serp:mewtwonite_y", name: "Mewtwonite Y" },
    { id: "serp:mini_lab", name: "Mini Lab" },
    { id: "serp:miracle_seed", name: "Miracle Seed" },
    { id: "serp:moltres_feather", name: "Moltres Feather" },
    { id: "serp:moomoo_milk", name: "Moomoo Milk" },
    { id: "serp:moon_stone", name: "Moon Stone" },
    { id: "serp:moonball", name: "Moonball" },
    { id: "serp:mystic_water", name: "Mystic Water" },
    { id: "serp:nanab_berry", name: "Nanab Berry" },
    { id: "serp:nestball", name: "Nestball" },
    { id: "serp:netball", name: "Netball" },
    { id: "serp:never_melt_ice", name: "Never Melt Ice" },
    { id: "serp:oran_berry", name: "Oran Berry" },
    { id: "serp:orange_apricorn", name: "Orange Apricorn" },
    { id: "serp:parkball", name: "Parkball" },
    { id: "serp:pc_box", name: "Pc Box" },
    { id: "serp:pecha_berry", name: "Pecha Berry" },
    { id: "serp:persim_berry", name: "Persim Berry" },
    { id: "serp:pichu_plush", name: "Pichu Plush" },
    { id: "serp:pidgeotite", name: "Pidgeotite" },
    { id: "serp:pinap_berry", name: "Pinap Berry" },
    { id: "serp:pink_apricorn", name: "Pink Apricorn" },
    { id: "serp:poison_barb", name: "Poison Barb" },
    { id: "serp:poke", name: "Poke" },
    { id: "serp:poke_ore", name: "Poke Ore" },
    { id: "serp:poke_ride", name: "Poke Ride" },
    { id: "serp:pokeball", name: "Pokeball" },
    { id: "serp:pokebike", name: "Pokebike" },
    { id: "serp:pokedex", name: "Pokedex" },
    { id: "serp:pokemon_egg", name: "Pokemon Egg" },
    { id: "serp:pokepuff_citrus", name: "Pokepuff Citrus" },
    { id: "serp:pokepuff_mint", name: "Pokepuff Mint" },
    { id: "serp:pokepuff_mocha", name: "Pokepuff Mocha" },
    { id: "serp:pokepuff_spice", name: "Pokepuff Spice" },
    { id: "serp:pokepuff_sweet", name: "Pokepuff Sweet" },
    { id: "serp:pomeg_berry", name: "Pomeg Berry" },
    { id: "serp:potion", name: "Potion" },
    { id: "serp:premierball", name: "Premierball" },
    { id: "serp:protein", name: "Protein" },
    { id: "serp:qualot_berry", name: "Qualot Berry" },
    { id: "serp:quickball", name: "Quickball" },
    { id: "serp:raikou_lock", name: "Raikou Lock" },
    { id: "serp:rare_candy", name: "Rare Candy" },
    { id: "serp:rawst_berry", name: "Rawst Berry" },
    { id: "serp:rayquaza_scale", name: "Rayquaza Scale" },
    { id: "serp:razz_berry", name: "Razz Berry" },
    { id: "serp:red_apricorn", name: "Red Apricorn" },
    { id: "serp:red_boots", name: "Red Boots" },
    { id: "serp:red_chestplate", name: "Red Chestplate" },
    { id: "serp:red_helmet", name: "Red Helmet" },
    { id: "serp:red_leggings", name: "Red Leggings" },
    { id: "serp:red_prism", name: "Red Prism" },
    { id: "serp:repeatball", name: "Repeatball" },
    { id: "serp:repel", name: "Repel" },
    { id: "serp:revive", name: "Revive" },
    { id: "serp:rindo_berry", name: "Rindo Berry" },
    { id: "serp:rocket_boots", name: "Rocket Boots" },
    { id: "serp:rocket_chestplate", name: "Rocket Chestplate" },
    { id: "serp:rocket_helmet", name: "Rocket Helmet" },
    { id: "serp:rocketf_leggings", name: "Rocketf Leggings" },
    { id: "serp:rocketm_leggings", name: "Rocketm Leggings" },
    { id: "serp:rotomarket", name: "Rotomarket" },
    { id: "serp:sablenite", name: "Sablenite" },
    { id: "serp:safariball", name: "Safariball" },
    { id: "serp:salamencite", name: "Salamencite" },
    { id: "serp:sceptilite", name: "Sceptilite" },
    { id: "serp:scizorite", name: "Scizorite" },
    { id: "serp:sharp_beak", name: "Sharp Beak" },
    { id: "serp:shellder_shell", name: "Shellder Shell" },
    { id: "serp:shiny_stone", name: "Shiny Stone" },
    { id: "serp:silk_scarf", name: "Silk Scarf" },
    { id: "serp:silver_powder", name: "Silver Powder" },
    { id: "serp:sitrus_berry", name: "Sitrus Berry" },
    { id: "serp:slot_machine", name: "Slot Machine" },
    { id: "serp:slowbronite", name: "Slowbronite" },
    { id: "serp:slowpoke_tail", name: "Slowpoke Tail" },
    { id: "serp:soda_pop", name: "Soda Pop" },
    { id: "serp:soft_sand", name: "Soft Sand" },
    { id: "serp:spell_tag", name: "Spell Tag" },
    { id: "serp:sportball", name: "Sportball" },
    { id: "serp:staraptite", name: "Staraptite" },
    { id: "serp:steelixite", name: "Steelixite" },
    { id: "serp:strangeball", name: "Strangeball" },
    { id: "serp:suicune_lock", name: "Suicune Lock" },
    { id: "serp:sun_stone", name: "Sun Stone" },
    { id: "serp:super_potion", name: "Super Potion" },
    { id: "serp:super_repel", name: "Super Repel" },
    { id: "serp:swampertite", name: "Swampertite" },
    { id: "serp:tamato_berry", name: "Tamato Berry" },
    { id: "serp:thunder_stone", name: "Thunder Stone" },
    { id: "serp:timerball", name: "Timerball" },
    { id: "serp:tm_1", name: "Tm 1" },
    { id: "serp:tm_10", name: "Tm 10" },
    { id: "serp:tm_11", name: "Tm 11" },
    { id: "serp:tm_12", name: "Tm 12" },
    { id: "serp:tm_13", name: "Tm 13" },
    { id: "serp:tm_14", name: "Tm 14" },
    { id: "serp:tm_15", name: "Tm 15" },
    { id: "serp:tm_16", name: "Tm 16" },
    { id: "serp:tm_17", name: "Tm 17" },
    { id: "serp:tm_18", name: "Tm 18" },
    { id: "serp:tm_2", name: "Tm 2" },
    { id: "serp:tm_3", name: "Tm 3" },
    { id: "serp:tm_4", name: "Tm 4" },
    { id: "serp:tm_5", name: "Tm 5" },
    { id: "serp:tm_6", name: "Tm 6" },
    { id: "serp:tm_7", name: "Tm 7" },
    { id: "serp:tm_8", name: "Tm 8" },
    { id: "serp:tm_9", name: "Tm 9" },
    { id: "serp:tm_machine", name: "Tm Machine" },
    { id: "serp:trade_machine", name: "Trade Machine" },
    { id: "serp:twisted_spoon", name: "Twisted Spoon" },
    { id: "serp:ultraball", name: "Ultraball" },
    { id: "serp:venusaurite", name: "Venusaurite" },
    { id: "serp:victini_lock", name: "Victini Lock" },
    { id: "serp:water_stone", name: "Water Stone" },
    { id: "serp:white_apricorn", name: "White Apricorn" },
    { id: "serp:wishing_shard", name: "Wishing Shard" },
    { id: "serp:wishing_star", name: "Wishing Star" },
    { id: "serp:xerneas_horn", name: "Xerneas Horn" },
    { id: "serp:yellow_apricorn", name: "Yellow Apricorn" },
    { id: "serp:yveltal_claw", name: "Yveltal Claw" },
    { id: "serp:zapdos_feather", name: "Zapdos Feather" },
    { id: "serp:zinc", name: "Zinc" },
];