// Curated vanilla Minecraft items/blocks for admin gifting & rewards
export const VANILLA_ITEMS = [
    { id: "minecraft:diamond", name: "Diamond (MC)" },
    { id: "minecraft:emerald", name: "Emerald (MC)" },
    { id: "minecraft:iron_ingot", name: "Iron Ingot (MC)" },
    { id: "minecraft:gold_ingot", name: "Gold Ingot (MC)" },
    { id: "minecraft:copper_ingot", name: "Copper Ingot (MC)" },
    { id: "minecraft:netherite_ingot", name: "Netherite Ingot (MC)" },
    { id: "minecraft:netherite_scrap", name: "Netherite Scrap (MC)" },
    { id: "minecraft:coal", name: "Coal (MC)" },
    { id: "minecraft:charcoal", name: "Charcoal (MC)" },
    { id: "minecraft:redstone", name: "Redstone (MC)" },
    { id: "minecraft:lapis_lazuli", name: "Lapis Lazuli (MC)" },
    { id: "minecraft:quartz", name: "Quartz (MC)" },
    { id: "minecraft:amethyst_shard", name: "Amethyst Shard (MC)" },
    { id: "minecraft:raw_iron", name: "Raw Iron (MC)" },
    { id: "minecraft:raw_gold", name: "Raw Gold (MC)" },
    { id: "minecraft:raw_copper", name: "Raw Copper (MC)" },
    { id: "minecraft:stick", name: "Stick (MC)" },
    { id: "minecraft:bone", name: "Bone (MC)" },
    { id: "minecraft:bone_meal", name: "Bone Meal (MC)" },
    { id: "minecraft:string", name: "String (MC)" },
    { id: "minecraft:feather", name: "Feather (MC)" },
    { id: "minecraft:leather", name: "Leather (MC)" },
    { id: "minecraft:rabbit_hide", name: "Rabbit Hide (MC)" },
    { id: "minecraft:flint", name: "Flint (MC)" },
    { id: "minecraft:gunpowder", name: "Gunpowder (MC)" },
    { id: "minecraft:blaze_rod", name: "Blaze Rod (MC)" },
    { id: "minecraft:blaze_powder", name: "Blaze Powder (MC)" },
    { id: "minecraft:ender_pearl", name: "Ender Pearl (MC)" },
    { id: "minecraft:ender_eye", name: "Ender Eye (MC)" },
    { id: "minecraft:ghast_tear", name: "Ghast Tear (MC)" },
    { id: "minecraft:slime_ball", name: "Slime Ball (MC)" },
    { id: "minecraft:magma_cream", name: "Magma Cream (MC)" },
    { id: "minecraft:nether_star", name: "Nether Star (MC)" },
    { id: "minecraft:dragon_breath", name: "Dragon Breath (MC)" },
    { id: "minecraft:prismarine_shard", name: "Prismarine Shard (MC)" },
    { id: "minecraft:prismarine_crystals", name: "Prismarine Crystals (MC)" },
    { id: "minecraft:nautilus_shell", name: "Nautilus Shell (MC)" },
    { id: "minecraft:heart_of_the_sea", name: "Heart Of The Sea (MC)" },
    { id: "minecraft:phantom_membrane", name: "Phantom Membrane (MC)" },
    { id: "minecraft:shulker_shell", name: "Shulker Shell (MC)" },
    { id: "minecraft:echo_shard", name: "Echo Shard (MC)" },
    { id: "minecraft:totem_of_undying", name: "Totem Of Undying (MC)" },
    { id: "minecraft:experience_bottle", name: "Experience Bottle (MC)" },
    { id: "minecraft:name_tag", name: "Name Tag (MC)" },
    { id: "minecraft:saddle", name: "Saddle (MC)" },
    { id: "minecraft:lead", name: "Lead (MC)" },
    { id: "minecraft:elytra", name: "Elytra (MC)" },
    { id: "minecraft:trident", name: "Trident (MC)" },
    { id: "minecraft:turtle_scute", name: "Turtle Scute (MC)" },
    { id: "minecraft:honeycomb", name: "Honeycomb (MC)" },
    { id: "minecraft:glow_ink_sac", name: "Glow Ink Sac (MC)" },
    { id: "minecraft:ink_sac", name: "Ink Sac (MC)" },
    { id: "minecraft:paper", name: "Paper (MC)" },
    { id: "minecraft:book", name: "Book (MC)" },
    { id: "minecraft:writable_book", name: "Writable Book (MC)" },
    { id: "minecraft:clock", name: "Clock (MC)" },
    { id: "minecraft:compass", name: "Compass (MC)" },
    { id: "minecraft:recovery_compass", name: "Recovery Compass (MC)" },
    { id: "minecraft:spyglass", name: "Spyglass (MC)" },
    { id: "minecraft:shears", name: "Shears (MC)" },
    { id: "minecraft:flint_and_steel", name: "Flint And Steel (MC)" },
    { id: "minecraft:fishing_rod", name: "Fishing Rod (MC)" },
    { id: "minecraft:bow", name: "Bow (MC)" },
    { id: "minecraft:crossbow", name: "Crossbow (MC)" },
    { id: "minecraft:arrow", name: "Arrow (MC)" },
    { id: "minecraft:shield", name: "Shield (MC)" },
    { id: "minecraft:snowball", name: "Snowball (MC)" },
    { id: "minecraft:egg", name: "Egg (MC)" },
    { id: "minecraft:bucket", name: "Bucket (MC)" },
    { id: "minecraft:water_bucket", name: "Water Bucket (MC)" },
    { id: "minecraft:lava_bucket", name: "Lava Bucket (MC)" },
    { id: "minecraft:milk_bucket", name: "Milk Bucket (MC)" },
    { id: "minecraft:glass_bottle", name: "Glass Bottle (MC)" },
    { id: "minecraft:brush", name: "Brush (MC)" },
    { id: "minecraft:goat_horn", name: "Goat Horn (MC)" },
    { id: "minecraft:apple", name: "Food Apple (MC)" },
    { id: "minecraft:golden_apple", name: "Food Golden Apple (MC)" },
    { id: "minecraft:enchanted_golden_apple", name: "Food Enchanted Golden Apple (MC)" },
    { id: "minecraft:bread", name: "Food Bread (MC)" },
    { id: "minecraft:cooked_beef", name: "Food Cooked Beef (MC)" },
    { id: "minecraft:cooked_porkchop", name: "Food Cooked Porkchop (MC)" },
    { id: "minecraft:cooked_chicken", name: "Food Cooked Chicken (MC)" },
    { id: "minecraft:cooked_mutton", name: "Food Cooked Mutton (MC)" },
    { id: "minecraft:cooked_rabbit", name: "Food Cooked Rabbit (MC)" },
    { id: "minecraft:cooked_cod", name: "Food Cooked Cod (MC)" },
    { id: "minecraft:cooked_salmon", name: "Food Cooked Salmon (MC)" },
    { id: "minecraft:baked_potato", name: "Food Baked Potato (MC)" },
    { id: "minecraft:carrot", name: "Food Carrot (MC)" },
    { id: "minecraft:golden_carrot", name: "Food Golden Carrot (MC)" },
    { id: "minecraft:potato", name: "Food Potato (MC)" },
    { id: "minecraft:beetroot", name: "Food Beetroot (MC)" },
    { id: "minecraft:melon_slice", name: "Food Melon Slice (MC)" },
    { id: "minecraft:sweet_berries", name: "Food Sweet Berries (MC)" },
    { id: "minecraft:glow_berries", name: "Food Glow Berries (MC)" },
    { id: "minecraft:pumpkin_pie", name: "Food Pumpkin Pie (MC)" },
    { id: "minecraft:cake", name: "Food Cake (MC)" },
    { id: "minecraft:cookie", name: "Food Cookie (MC)" },
    { id: "minecraft:honey_bottle", name: "Food Honey Bottle (MC)" },
    { id: "minecraft:mushroom_stew", name: "Food Mushroom Stew (MC)" },
    { id: "minecraft:rabbit_stew", name: "Food Rabbit Stew (MC)" },
    { id: "minecraft:beetroot_soup", name: "Food Beetroot Soup (MC)" },
    { id: "minecraft:dried_kelp", name: "Food Dried Kelp (MC)" },
    { id: "minecraft:chorus_fruit", name: "Food Chorus Fruit (MC)" },
    { id: "minecraft:diamond_sword", name: "Tool Diamond Sword (MC)" },
    { id: "minecraft:diamond_pickaxe", name: "Tool Diamond Pickaxe (MC)" },
    { id: "minecraft:diamond_axe", name: "Tool Diamond Axe (MC)" },
    { id: "minecraft:diamond_shovel", name: "Tool Diamond Shovel (MC)" },
    { id: "minecraft:diamond_hoe", name: "Tool Diamond Hoe (MC)" },
    { id: "minecraft:netherite_sword", name: "Tool Netherite Sword (MC)" },
    { id: "minecraft:netherite_pickaxe", name: "Tool Netherite Pickaxe (MC)" },
    { id: "minecraft:netherite_axe", name: "Tool Netherite Axe (MC)" },
    { id: "minecraft:netherite_shovel", name: "Tool Netherite Shovel (MC)" },
    { id: "minecraft:netherite_hoe", name: "Tool Netherite Hoe (MC)" },
    { id: "minecraft:iron_sword", name: "Tool Iron Sword (MC)" },
    { id: "minecraft:iron_pickaxe", name: "Tool Iron Pickaxe (MC)" },
    { id: "minecraft:iron_axe", name: "Tool Iron Axe (MC)" },
    { id: "minecraft:iron_shovel", name: "Tool Iron Shovel (MC)" },
    { id: "minecraft:iron_hoe", name: "Tool Iron Hoe (MC)" },
    { id: "minecraft:golden_sword", name: "Tool Golden Sword (MC)" },
    { id: "minecraft:golden_pickaxe", name: "Tool Golden Pickaxe (MC)" },
    { id: "minecraft:diamond_helmet", name: "Armor Diamond Helmet (MC)" },
    { id: "minecraft:diamond_chestplate", name: "Armor Diamond Chestplate (MC)" },
    { id: "minecraft:diamond_leggings", name: "Armor Diamond Leggings (MC)" },
    { id: "minecraft:diamond_boots", name: "Armor Diamond Boots (MC)" },
    { id: "minecraft:netherite_helmet", name: "Armor Netherite Helmet (MC)" },
    { id: "minecraft:netherite_chestplate", name: "Armor Netherite Chestplate (MC)" },
    { id: "minecraft:netherite_leggings", name: "Armor Netherite Leggings (MC)" },
    { id: "minecraft:netherite_boots", name: "Armor Netherite Boots (MC)" },
    { id: "minecraft:iron_helmet", name: "Armor Iron Helmet (MC)" },
    { id: "minecraft:iron_chestplate", name: "Armor Iron Chestplate (MC)" },
    { id: "minecraft:iron_leggings", name: "Armor Iron Leggings (MC)" },
    { id: "minecraft:iron_boots", name: "Armor Iron Boots (MC)" },
    { id: "minecraft:golden_helmet", name: "Armor Golden Helmet (MC)" },
    { id: "minecraft:golden_chestplate", name: "Armor Golden Chestplate (MC)" },
    { id: "minecraft:golden_leggings", name: "Armor Golden Leggings (MC)" },
    { id: "minecraft:golden_boots", name: "Armor Golden Boots (MC)" },
    { id: "minecraft:leather_helmet", name: "Armor Leather Helmet (MC)" },
    { id: "minecraft:leather_chestplate", name: "Armor Leather Chestplate (MC)" },
    { id: "minecraft:leather_leggings", name: "Armor Leather Leggings (MC)" },
    { id: "minecraft:leather_boots", name: "Armor Leather Boots (MC)" },
    { id: "minecraft:stone", name: "Block Stone (MC)" },
    { id: "minecraft:cobblestone", name: "Block Cobblestone (MC)" },
    { id: "minecraft:deepslate", name: "Block Deepslate (MC)" },
    { id: "minecraft:cobbled_deepslate", name: "Block Cobbled Deepslate (MC)" },
    { id: "minecraft:granite", name: "Block Granite (MC)" },
    { id: "minecraft:diorite", name: "Block Diorite (MC)" },
    { id: "minecraft:andesite", name: "Block Andesite (MC)" },
    { id: "minecraft:calcite", name: "Block Calcite (MC)" },
    { id: "minecraft:tuff", name: "Block Tuff (MC)" },
    { id: "minecraft:dirt", name: "Block Dirt (MC)" },
    { id: "minecraft:grass_block", name: "Block Grass Block (MC)" },
    { id: "minecraft:podzol", name: "Block Podzol (MC)" },
    { id: "minecraft:mycelium", name: "Block Mycelium (MC)" },
    { id: "minecraft:mud", name: "Block Mud (MC)" },
    { id: "minecraft:clay", name: "Block Clay (MC)" },
    { id: "minecraft:sand", name: "Block Sand (MC)" },
    { id: "minecraft:red_sand", name: "Block Red Sand (MC)" },
    { id: "minecraft:gravel", name: "Block Gravel (MC)" },
    { id: "minecraft:sandstone", name: "Block Sandstone (MC)" },
    { id: "minecraft:red_sandstone", name: "Block Red Sandstone (MC)" },
    { id: "minecraft:obsidian", name: "Block Obsidian (MC)" },
    { id: "minecraft:crying_obsidian", name: "Block Crying Obsidian (MC)" },
    { id: "minecraft:bedrock", name: "Block Bedrock (MC)" },
    { id: "minecraft:netherrack", name: "Block Netherrack (MC)" },
    { id: "minecraft:soul_sand", name: "Block Soul Sand (MC)" },
    { id: "minecraft:soul_soil", name: "Block Soul Soil (MC)" },
    { id: "minecraft:basalt", name: "Block Basalt (MC)" },
    { id: "minecraft:blackstone", name: "Block Blackstone (MC)" },
    { id: "minecraft:end_stone", name: "Block End Stone (MC)" },
    { id: "minecraft:purpur_block", name: "Block Purpur Block (MC)" },
    { id: "minecraft:prismarine", name: "Block Prismarine (MC)" },
    { id: "minecraft:dark_prismarine", name: "Block Dark Prismarine (MC)" },
    { id: "minecraft:sea_lantern", name: "Block Sea Lantern (MC)" },
    { id: "minecraft:glowstone", name: "Block Glowstone (MC)" },
    { id: "minecraft:shroomlight", name: "Block Shroomlight (MC)" },
    { id: "minecraft:ochre_froglight", name: "Block Ochre Froglight (MC)" },
    { id: "minecraft:verdant_froglight", name: "Block Verdant Froglight (MC)" },
    { id: "minecraft:pearlescent_froglight", name: "Block Pearlescent Froglight (MC)" },
    { id: "minecraft:glass", name: "Block Glass (MC)" },
    { id: "minecraft:tinted_glass", name: "Block Tinted Glass (MC)" },
    { id: "minecraft:white_stained_glass", name: "Block White Stained Glass (MC)" },
    { id: "minecraft:ice", name: "Block Ice (MC)" },
    { id: "minecraft:packed_ice", name: "Block Packed Ice (MC)" },
    { id: "minecraft:blue_ice", name: "Block Blue Ice (MC)" },
    { id: "minecraft:snow", name: "Block Snow (MC)" },
    { id: "minecraft:bookshelf", name: "Block Bookshelf (MC)" },
    { id: "minecraft:chiseled_bookshelf", name: "Block Chiseled Bookshelf (MC)" },
    { id: "minecraft:lectern", name: "Block Lectern (MC)" },
    { id: "minecraft:crafting_table", name: "Block Crafting Table (MC)" },
    { id: "minecraft:furnace", name: "Block Furnace (MC)" },
    { id: "minecraft:blast_furnace", name: "Block Blast Furnace (MC)" },
    { id: "minecraft:smoker", name: "Block Smoker (MC)" },
    { id: "minecraft:anvil", name: "Block Anvil (MC)" },
    { id: "minecraft:grindstone", name: "Block Grindstone (MC)" },
    { id: "minecraft:smithing_table", name: "Block Smithing Table (MC)" },
    { id: "minecraft:cartography_table", name: "Block Cartography Table (MC)" },
    { id: "minecraft:fletching_table", name: "Block Fletching Table (MC)" },
    { id: "minecraft:loom", name: "Block Loom (MC)" },
    { id: "minecraft:stonecutter_block", name: "Block Stonecutter Block (MC)" },
    { id: "minecraft:enchanting_table", name: "Block Enchanting Table (MC)" },
    { id: "minecraft:brewing_stand", name: "Block Brewing Stand (MC)" },
    { id: "minecraft:cauldron", name: "Block Cauldron (MC)" },
    { id: "minecraft:composter", name: "Block Composter (MC)" },
    { id: "minecraft:barrel", name: "Block Barrel (MC)" },
    { id: "minecraft:chest", name: "Block Chest (MC)" },
    { id: "minecraft:trapped_chest", name: "Block Trapped Chest (MC)" },
    { id: "minecraft:ender_chest", name: "Block Ender Chest (MC)" },
    { id: "minecraft:shulker_box", name: "Block Shulker Box (MC)" },
    { id: "minecraft:hopper", name: "Block Hopper (MC)" },
    { id: "minecraft:dropper", name: "Block Dropper (MC)" },
    { id: "minecraft:dispenser", name: "Block Dispenser (MC)" },
    { id: "minecraft:observer", name: "Block Observer (MC)" },
    { id: "minecraft:piston", name: "Block Piston (MC)" },
    { id: "minecraft:sticky_piston", name: "Block Sticky Piston (MC)" },
    { id: "minecraft:redstone_block", name: "Block Redstone Block (MC)" },
    { id: "minecraft:redstone_lamp", name: "Block Redstone Lamp (MC)" },
    { id: "minecraft:redstone_torch", name: "Block Redstone Torch (MC)" },
    { id: "minecraft:repeater", name: "Block Repeater (MC)" },
    { id: "minecraft:comparator", name: "Block Comparator (MC)" },
    { id: "minecraft:daylight_detector", name: "Block Daylight Detector (MC)" },
    { id: "minecraft:target", name: "Block Target (MC)" },
    { id: "minecraft:lever", name: "Block Lever (MC)" },
    { id: "minecraft:tnt", name: "Block Tnt (MC)" },
    { id: "minecraft:beacon", name: "Block Beacon (MC)" },
    { id: "minecraft:conduit", name: "Block Conduit (MC)" },
    { id: "minecraft:lodestone", name: "Block Lodestone (MC)" },
    { id: "minecraft:respawn_anchor", name: "Block Respawn Anchor (MC)" },
    { id: "minecraft:scaffolding", name: "Block Scaffolding (MC)" },
    { id: "minecraft:ladder", name: "Block Ladder (MC)" },
    { id: "minecraft:torch", name: "Block Torch (MC)" },
    { id: "minecraft:soul_torch", name: "Block Soul Torch (MC)" },
    { id: "minecraft:lantern", name: "Block Lantern (MC)" },
    { id: "minecraft:soul_lantern", name: "Block Soul Lantern (MC)" },
    { id: "minecraft:campfire", name: "Block Campfire (MC)" },
    { id: "minecraft:soul_campfire", name: "Block Soul Campfire (MC)" },
    { id: "minecraft:bell", name: "Block Bell (MC)" },
    { id: "minecraft:iron_block", name: "Block Iron Block (MC)" },
    { id: "minecraft:gold_block", name: "Block Gold Block (MC)" },
    { id: "minecraft:diamond_block", name: "Block Diamond Block (MC)" },
    { id: "minecraft:emerald_block", name: "Block Emerald Block (MC)" },
    { id: "minecraft:netherite_block", name: "Block Netherite Block (MC)" },
    { id: "minecraft:copper_block", name: "Block Copper Block (MC)" },
    { id: "minecraft:coal_block", name: "Block Coal Block (MC)" },
    { id: "minecraft:lapis_block", name: "Block Lapis Block (MC)" },
    { id: "minecraft:quartz_block", name: "Block Quartz Block (MC)" },
    { id: "minecraft:amethyst_block", name: "Block Amethyst Block (MC)" },
    { id: "minecraft:hay_block", name: "Block Hay Block (MC)" },
    { id: "minecraft:bone_block", name: "Block Bone Block (MC)" },
    { id: "minecraft:slime", name: "Block Slime (MC)" },
    { id: "minecraft:honey_block", name: "Block Honey Block (MC)" },
    { id: "minecraft:dried_kelp_block", name: "Block Dried Kelp Block (MC)" },
    { id: "minecraft:melon_block", name: "Block Melon Block (MC)" },
    { id: "minecraft:pumpkin", name: "Block Pumpkin (MC)" },
    { id: "minecraft:carved_pumpkin", name: "Block Carved Pumpkin (MC)" },
    { id: "minecraft:lit_pumpkin", name: "Block Lit Pumpkin (MC)" },
    { id: "minecraft:cactus", name: "Block Cactus (MC)" },
    { id: "minecraft:bamboo", name: "Block Bamboo (MC)" },
    { id: "minecraft:sugar_cane", name: "Block Sugar Cane (MC)" },
    { id: "minecraft:cobweb", name: "Block Cobweb (MC)" },
    { id: "minecraft:sponge", name: "Block Sponge (MC)" },
    { id: "minecraft:wet_sponge", name: "Block Wet Sponge (MC)" },
    { id: "minecraft:oak_log", name: "Wood Oak Log (MC)" },
    { id: "minecraft:spruce_log", name: "Wood Spruce Log (MC)" },
    { id: "minecraft:birch_log", name: "Wood Birch Log (MC)" },
    { id: "minecraft:jungle_log", name: "Wood Jungle Log (MC)" },
    { id: "minecraft:acacia_log", name: "Wood Acacia Log (MC)" },
    { id: "minecraft:dark_oak_log", name: "Wood Dark Oak Log (MC)" },
    { id: "minecraft:mangrove_log", name: "Wood Mangrove Log (MC)" },
    { id: "minecraft:cherry_log", name: "Wood Cherry Log (MC)" },
    { id: "minecraft:crimson_stem", name: "Wood Crimson Stem (MC)" },
    { id: "minecraft:warped_stem", name: "Wood Warped Stem (MC)" },
    { id: "minecraft:oak_planks", name: "Wood Oak Planks (MC)" },
    { id: "minecraft:spruce_planks", name: "Wood Spruce Planks (MC)" },
    { id: "minecraft:birch_planks", name: "Wood Birch Planks (MC)" },
    { id: "minecraft:jungle_planks", name: "Wood Jungle Planks (MC)" },
    { id: "minecraft:acacia_planks", name: "Wood Acacia Planks (MC)" },
    { id: "minecraft:dark_oak_planks", name: "Wood Dark Oak Planks (MC)" },
    { id: "minecraft:mangrove_planks", name: "Wood Mangrove Planks (MC)" },
    { id: "minecraft:cherry_planks", name: "Wood Cherry Planks (MC)" },
    { id: "minecraft:bamboo_planks", name: "Wood Bamboo Planks (MC)" },
    { id: "minecraft:crimson_planks", name: "Wood Crimson Planks (MC)" },
    { id: "minecraft:warped_planks", name: "Wood Warped Planks (MC)" },
    { id: "minecraft:oak_fence", name: "Wood Oak Fence (MC)" },
    { id: "minecraft:oak_door", name: "Wood Oak Door (MC)" },
    { id: "minecraft:iron_door", name: "Wood Iron Door (MC)" },
    { id: "minecraft:oak_trapdoor", name: "Wood Oak Trapdoor (MC)" },
    { id: "minecraft:oak_stairs", name: "Wood Oak Stairs (MC)" },
    { id: "minecraft:stone_stairs", name: "Wood Stone Stairs (MC)" },
    { id: "minecraft:oak_slab", name: "Wood Oak Slab (MC)" },
    { id: "minecraft:white_wool", name: "Wool White Wool (MC)" },
    { id: "minecraft:black_wool", name: "Wool Black Wool (MC)" },
    { id: "minecraft:red_wool", name: "Wool Red Wool (MC)" },
    { id: "minecraft:blue_wool", name: "Wool Blue Wool (MC)" },
    { id: "minecraft:green_wool", name: "Wool Green Wool (MC)" },
    { id: "minecraft:yellow_wool", name: "Wool Yellow Wool (MC)" },
    { id: "minecraft:orange_wool", name: "Wool Orange Wool (MC)" },
    { id: "minecraft:purple_wool", name: "Wool Purple Wool (MC)" },
    { id: "minecraft:pink_wool", name: "Wool Pink Wool (MC)" },
    { id: "minecraft:cyan_wool", name: "Wool Cyan Wool (MC)" },
    { id: "minecraft:light_blue_wool", name: "Wool Light Blue Wool (MC)" },
    { id: "minecraft:lime_wool", name: "Wool Lime Wool (MC)" },
    { id: "minecraft:magenta_wool", name: "Wool Magenta Wool (MC)" },
    { id: "minecraft:brown_wool", name: "Wool Brown Wool (MC)" },
    { id: "minecraft:gray_wool", name: "Wool Gray Wool (MC)" },
    { id: "minecraft:light_gray_wool", name: "Wool Light Gray Wool (MC)" },
    { id: "minecraft:white_carpet", name: "Wool White Carpet (MC)" },
    { id: "minecraft:bed", name: "Bed (MC)" },
    { id: "minecraft:wheat_seeds", name: "Farm Wheat Seeds (MC)" },
    { id: "minecraft:wheat", name: "Farm Wheat (MC)" },
    { id: "minecraft:beetroot_seeds", name: "Farm Beetroot Seeds (MC)" },
    { id: "minecraft:pumpkin_seeds", name: "Farm Pumpkin Seeds (MC)" },
    { id: "minecraft:melon_seeds", name: "Farm Melon Seeds (MC)" },
    { id: "minecraft:oak_sapling", name: "Farm Oak Sapling (MC)" },
    { id: "minecraft:spruce_sapling", name: "Farm Spruce Sapling (MC)" },
    { id: "minecraft:birch_sapling", name: "Farm Birch Sapling (MC)" },
    { id: "minecraft:cherry_sapling", name: "Farm Cherry Sapling (MC)" },
    { id: "minecraft:kelp", name: "Farm Kelp (MC)" },
    { id: "minecraft:brown_mushroom", name: "Farm Brown Mushroom (MC)" },
    { id: "minecraft:red_mushroom", name: "Farm Red Mushroom (MC)" },
    { id: "minecraft:nether_wart", name: "Farm Nether Wart (MC)" },
];